import { Metadata } from "next";
import { Nanum_Pen_Script } from "next/font/google";
import localFont from "next/font/local";

export const nanumPenScript = Nanum_Pen_Script({ weight: "400" });

export const doldam = localFont({
  src: [
    {
      path: "../asset/fonts/doldam.woff2",
    },
    {
      path: "../asset/fonts/doldam.woff",
    },
  ],
});

export const metadata: Metadata = {
  title: {
    template: "%s | PPP",
    default: "Next.js | PPP",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
