import { Metadata } from "next";

/* export const metadata: Metadata = {
  title: {
    template: "@s | PPP",
    default: "Next.js",
  },
  description: "Generated by Next.js",
}; */

export function generateMetadata(): Metadata {
  // 비동신 통신의 결과를 메타데이터의 정보로 활용할 수 있다.
  return {
    title: {
      template: "%s | PPP",
      default: "Next.js",
    },
    description: "Generated by Next.js",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1>Header</h1>
        </header>
        {children}
        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
